# Generated by Django 4.2.6 on 2023-11-06 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_book_readingprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publication_date',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
    ]
