# Generated by Django 4.2.6 on 2023-11-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_book_publication_date_remove_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingprogress',
            name='page_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
