# Generated by Django 4.2.6 on 2023-11-07 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
