# Generated by Django 4.2.6 on 2023-11-07 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
