# Generated by Django 4.2.6 on 2023-11-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingprogress',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
