# Generated by Django 4.2.6 on 2023-11-11 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_readingprogress_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingprogress',
            name='completed',
        ),
    ]
